name: Rndnumber Workflow
on: 
  release:
    types: [published]
jobs:
  Push_To_Docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.release.name}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_PASS}}
    - name: Echo name
      run: echo ${{ secrets.DOCKERHUB_USERNAME}}/random_numbers:${{github.event.release.name}}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME}}/random_numbers:${{github.event.release.name}}

