name: Rndnumber Workflow
on: 
  release:
    types: [published]
jobs:
  Push_To_Docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.release.name}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_PASS}}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME}}/random_numbers:${{github.event.release.name}}
  Notify_Slack:
    steps:
    - name: Send JSON data to slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text" : "Name:${{ secrets.NOTIFY_NAME }}\nMatriculation:${{ secrets.NOTIFY_MATRICULATION }}\nEmail:${{ secrets.NOTIFY_EMAIL }}\nRepo: git://github.com/e0941870/randnum.git \nImage name:${{ secrets.DOCKERHUB_USERNAME }}/random_numbers:${{github.event.release.name}}\nImage url:${{ secrets.DOCKERHUB_URL }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

